; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WinActivator"
#define MyAppVersion "2.0.0"
#define MyAppPublisher "ZubairComputerLab"
#define MyAppExeName "WinActivator.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E7C94829-0BB4-4C6B-B042-35C6456742B7}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\zubai\OneDrive\Desktop\WinActivatorApp
OutputBaseFilename=WinActivator
SetupIconFile=C:\Users\zubai\OneDrive\Desktop\WinActivator\winactivator.ico
Password=zubairkhan
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\Microsoft.Xaml.Behaviors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\Microsoft.Xaml.Behaviors.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\Microsoft.Xaml.Behaviors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\System.CodeDom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\System.CodeDom.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\WinActivator.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\zubai\OneDrive\Desktop\WinActivator\bin\Release\WinActivator.pdb"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

